version: '3.4'
services:
    mongo:
        image: 'mongo'
        ports:
            - '27020:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: happy2code
        volumes:
            - ./data/mongo:/data/db
        command: --auth
    api:
        build:
            context: ./bienxanh-api/
            args:
                - NODE_ENV=development
        command: /bin/bash -c "yarn run dev"
        ports:
            - '4000:4000'
        environment:
            - MONGO_URL=mongodb://admin:happy2code@mongo:27017/bienxanh?authSource=admin
        volumes:
            - ./bienxanh-api:/opt/app
            - /opt/app/node_modules
        depends_on:
            - mongo
    web:
        build:
            context: ./bienxanh/
            args:
                - NODE_ENV=development
        command: /bin/bash -c "yarn run start"
        ports:
            - '3000:3000'
        volumes:
            - ./bienxanh:/opt/app
            - /opt/app/node_modules
        depends_on:
            - api
